spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/foodstore
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

cache:
  config:
    entryTtl: 60
    products:
      entryTtl: 36000

springdoc:
  swagger-ui:
    path: /swagger

jwt:
  token:
    secret-key: d12ef765cf731897283ba2845488b8e41f8b10d275268249d80d9419a46d315f
    expiration-mills: 3600000